name: Does it work?

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: git config --global user.email "szymon.rusiecki@proton.me" && git config --global user.name "Rusiek" && git fetch && git checkout ${{ github.sha }}

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cd frontend && npm install && npm run build && npm run lint && git checkout -b @rusiek/lint && git add -A . && git diff-index --quiet HEAD || git commit --allow-empty -m "Lint code" && git push origin HEAD:@rusiek/lint
          
      - name: Set up spring
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: cd backend && ./gradlew build && ./gradlew check && git checkout -b @rusiek/lint && git add -A . && git diff-index --quiet HEAD || git commit --allow-empty -m "Lint code" && git push origin HEAD:@rusiek/lint
          
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: cd data_microservice && pip install -r requirements.txt && pylint app.py && git checkout -b @rusiek/lint && git add -A . && git diff-index --quiet HEAD || git commit --allow-empty -m "Lint code" && git push origin HEAD:@rusiek/lint
