name: Check backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      with:
         working-directory: ./backend
    - name: Run the Gradle package task
      uses: gradle/gradle-build-action@v2
      with:
        working-directory: ./backend
        arguments: -b ci.gradle package