name: Does it work?

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cd frontend && npm install && npm run build && npm run lint && git add . && git diff-index --quiet HEAD || git commit -m "Lint code" && git push
          
      - name: Set up spring
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: cd backend && ./gradlew build && ./gradlew check && git add . && git diff-index --quiet HEAD || git commit -m "Lint code" && git push
          
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: cd data_microservice && pip install -r requirements.txt && pylint app.py && git add . && git diff-index --quiet HEAD || git commit -m "Lint code" && git push
