name: Does it works?

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          run: | 
            cd frontend
            npm install
          
      - name: Set up spring
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          run: | 
            cd backend
            ./gradlew build

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          run: | 
            cd data_microservice
            pip install -r requirements.txt
